### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by huazhiyeluo** [andkom/php-berkeley-db#1]
Build PHP with db4 support:： make
/bin/sh /usr/local/soft/db-6.2.23/lang/php_db4/libtool --mode=compile g++  -I. -I/usr/local/soft/db-6.2.23/lang/php_db4 -DPHP_ATOM_INC -I/usr/local/soft/db-6.2.23/lang/php_db4/include -I/usr/local/soft/db-6.2.23/lang/php_db4/main -I/usr/local/soft/db-6.2.23/lang/php_db4 -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/usr/local/BerkeleyDB.6.2/include  -DHAVE_CONFIG_H  -g -O2   -c /usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp -o db4.lo
 g++ -I. -I/usr/local/soft/db-6.2.23/lang/php_db4 -DPHP_ATOM_INC -I/usr/local/soft/db-6.2.23/lang/php_db4/include -I/usr/local/soft/db-6.2.23/lang/php_db4/main -I/usr/local/soft/db-6.2.23/lang/php_db4 -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/usr/local/BerkeleyDB.6.2/include -DHAVE_CONFIG_H -g -O2 -c /usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp  -fPIC -DPIC -o .libs/db4.o
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:1059:34: error: macro "RETURN_STRING" passed 2 arguments, but takes just 1
     RETURN_STRING((char *)name, 1);
                                  ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:1136:46: error: macro "add_property_string" passed 4 arguments, but takes just 3
     add_property_string(self, "file", file, 1);
                                              ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:1137:54: error: macro "add_property_string" passed 4 arguments, but takes just 3
     add_property_string(self, "database", database, 1);
                                                      ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:1146:67: error: macro "add_property_string" passed 4 arguments, but takes just 3
         add_property_string(self, "lastError", db_strerror(ret), 1);
                                                                   ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:1225:57: error: macro "RETURN_STRINGL" passed 3 arguments, but takes just 2
         RETURN_STRINGL((char *)value.data, value.size, 1);
                                                         ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:1267:57: error: macro "RETURN_STRINGL" passed 3 arguments, but takes just 2
         RETURN_STRINGL((char *)value.data, value.size, 1);
                                                         ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:1286:40: error: macro "RETURN_STRING" passed 2 arguments, but takes just 1
             RETURN_STRING("DB_BTREE", 1);
                                        ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:1289:39: error: macro "RETURN_STRING" passed 2 arguments, but takes just 1
             RETURN_STRING("DB_HASH", 1);
                                       ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:1292:40: error: macro "RETURN_STRING" passed 2 arguments, but takes just 1
             RETURN_STRING("DB_RECNO", 1);
                                        ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:1295:40: error: macro "RETURN_STRING" passed 2 arguments, but takes just 1
             RETURN_STRING("DB_QUEUE", 1);
                                        ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:1298:39: error: macro "RETURN_STRING" passed 2 arguments, but takes just 1
             RETURN_STRING("UNKNOWN", 1);
                                       ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:1515:67: error: macro "add_property_string" passed 4 arguments, but takes just 3
         add_property_string(self, "lastError", db_strerror(ret), 1);
                                                                   ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:1585:67: error: macro "add_property_string" passed 4 arguments, but takes just 3
         add_property_string(self, "lastError", db_strerror(ret), 1);
                                                                   ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:1701:69: error: macro "ZVAL_STRINGL" passed 4 arguments, but takes just 3
   zval_dtor(zkey); ZVAL_STRINGL(zkey, (char *) key.data, key.size, 1);
                                                                     ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:1702:77: error: macro "ZVAL_STRINGL" passed 4 arguments, but takes just 3
   zval_dtor(zvalue); ZVAL_STRINGL(zvalue, (char *) value.data, value.size, 1);
                                                                             ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:1707:64: error: macro "add_property_string" passed 4 arguments, but takes just 3
      add_property_string(self, "lastError", db_strerror(ret), 1);
                                                                ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:1740:69: error: macro "ZVAL_STRINGL" passed 4 arguments, but takes just 3
   zval_dtor(zkey); ZVAL_STRINGL(zkey, (char *) key.data, key.size, 1);
                                                                     ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:1741:73: error: macro "ZVAL_STRINGL" passed 4 arguments, but takes just 3
   zval_dtor(zpkey); ZVAL_STRINGL(zpkey, (char *) pkey.data, pkey.size, 1);
                                                                         ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:1742:77: error: macro "ZVAL_STRINGL" passed 4 arguments, but takes just 3
   zval_dtor(zvalue); ZVAL_STRINGL(zvalue, (char *) value.data, value.size, 1);
                                                                             ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:1747:64: error: macro "add_property_string" passed 4 arguments, but takes just 3
      add_property_string(self, "lastError", db_strerror(ret), 1);
                                                                ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:1924:62: error: macro "add_property_stringl" passed 5 arguments, but takes just 4
  if(home) add_property_stringl(self, "home", home, homelen, 1);
                                                              ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:2026:67: error: macro "add_property_string" passed 4 arguments, but takes just 3
         add_property_string(self, "lastError", db_strerror(ret), 1);
                                                                   ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:2055:67: error: macro "add_property_string" passed 4 arguments, but takes just 3
         add_property_string(self, "lastError", db_strerror(ret), 1);
                                                                   ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:60:30: error: variable or field ‘_free_php_db_txn’ declared void
 static void _free_php_db_txn(zend_rsrc_list_entry *rsrc TSRMLS_DC)
                              ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:60:30: error: ‘zend_rsrc_list_entry’ was not declared in this scope
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:60:52: error: ‘rsrc’ was not declared in this scope
 static void _free_php_db_txn(zend_rsrc_list_entry *rsrc TSRMLS_DC)
                                                    ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:69:27: error: variable or field ‘_free_php_dbc’ declared void
 static void _free_php_dbc(zend_rsrc_list_entry *rsrc TSRMLS_DC)
                           ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:69:27: error: ‘zend_rsrc_list_entry’ was not declared in this scope
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:69:49: error: ‘rsrc’ was not declared in this scope
 static void _free_php_dbc(zend_rsrc_list_entry *rsrc TSRMLS_DC)
                                                 ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:77:26: error: variable or field ‘_free_php_db’ declared void
 static void _free_php_db(zend_rsrc_list_entry *rsrc TSRMLS_DC)
                          ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:77:26: error: ‘zend_rsrc_list_entry’ was not declared in this scope
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:77:48: error: ‘rsrc’ was not declared in this scope
 static void _free_php_db(zend_rsrc_list_entry *rsrc TSRMLS_DC)
                                                ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:85:29: error: variable or field ‘_free_php_dbenv’ declared void
 static void _free_php_dbenv(zend_rsrc_list_entry *rsrc TSRMLS_DC)
                             ^
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:85:29: error: ‘zend_rsrc_list_entry’ was not declared in this scope
/usr/local/soft/db-6.2.23/lang/php_db4/db4.cpp:85:51: error: ‘rsrc’ was not declared in this scope
 static void _free_php_dbenv(zend_rsrc_list_entry *rsrc TSRMLS_DC)
                                                   ^
make: *** [db4.lo] Error 1

**Comment by andkom** [comment]
try db4 library 4.8.30, 
php_db4 extension 18.1.25

**Comment by huazhiyeluo** [comment]
Thank you, sorry, not English, Google translation, I will try to see the effect

**Comment by andkom** [comment]
> Thank you, sorry, not English, Google translation, I will try to see the effect

Also you can check Dockerfile for hints

**Comment by huazhiyeluo** [comment]
Still reporting similar errors above
PHP 7.2.8 (cli) (built: Sep 24 2018 02:11:44) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by huazhiyeluo** [comment]
Does it not support PHP7?

**Comment by andkom** [comment]
> Does it not support PHP7?

Sure, check Dockerfile for configuration: https://github.com/andkom/php-berkeley-db/blob/master/Dockerfile

**Comment by huazhiyeluo** [comment]
I failed, sadness flows into the river！

**Comment by huazhiyeluo** [comment]
Finally, I succeeded, thank you for your help. I may have missed some basic libraries before.

**Comment by andkom** [comment]
ok

**Comment by huazhiyeluo** [comment]
thank you for your help
